[package]
name = "asus_windows_api"
version = "0.1.0"
edition = "2024"

[dependencies]
libloading = "0.9.0"
thiserror = "2.0"
windows-sys = { version = "0.61.2", features = [
  "Win32",
  "Win32_Storage_Packaging_Appx",
] }
