[workspace]
resolver = "3"
members = [
    "azizo",
    "azizo-core",
]

[workspace.package]
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/abd0-omar/azizo"
repository = "https://github.com/abd0-omar/azizo"
